require 'pry'
require 'open-uri'
require 'nokogiri'
require 'colorize'
require_relative "./bestseller/version"
require_relative "./bestseller/cli"
require_relative "./bestseller/books"
require_relative "./bestseller/categories"
require_relative "./bestseller/scraper"
